### ISSUE TITLE
[BUG]: Config/Export after deleting the storage directory crashes the app

### ISSUE THREAD

**Issue by kamathprasad9** [PhenoApps/Field-Book#1061]
### Description

```
Process: com.fieldbook.tracker, PID: 23424
                            java.util.NoSuchElementException: List is empty.
                            	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:214)
                            	at com.fieldbook.tracker.utilities.ExportUtil.handleExportResult(ExportUtil.kt:539)
                            	at com.fieldbook.tracker.utilities.ExportUtil.access$handleExportResult(ExportUtil.kt:48)
                            	at com.fieldbook.tracker.utilities.ExportUtil$startExportTasks$1$1.invokeSuspend(ExportUtil.kt:351)
                            	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                            	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                            	at android.os.Handler.handleCallback(Handler.java:959)
                            	at android.os.Handler.dispatchMessage(Handler.java:100)
                            	at android.os.Looper.loopOnce(Looper.java:232)
                            	at android.os.Looper.loop(Looper.java:317)
                            	at android.app.ActivityThread.main(ActivityThread.java:8699)
                            	at java.lang.reflect.Method.invoke(Native Method)
                            	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                            	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
                            	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2e942ce, Dispatchers.IO]
```

**Comment by chaneylc** [comment]
I can't reproduce this on the latest version, please reopen this if it occurs again for you.

**Comment by kamathprasad9** [comment]
I can still see this on the latest version.

Here's what I did:
1. Open up the app, stay on the home page of the app (config activity)
2. Without killing the app, switch to the device's file manager and delete the storage directory
3. Switch back to the app and try doing Config/Export

This is just an extreme case - highly unlikely to happen

**Comment by kamathprasad9** [comment]
Taking a similar approach for settings/database/export gives a success toast message to the user - but the db file is never saved in the device
