### ISSUE TITLE
[BUG]: App crashes when navigating to collect screen when field is not changed on initial startup. 

### ISSUE THREAD

**Issue by hkmanching** [PhenoApps/Field-Book#1066]
### Description

When fieldbook is opened and a field is already selected at startup (maybe from previous use), if you click "Collect," the app crashes. This does not happen if you navigate to a different field. Does not happen in version 5.6.24. 

### Field Book version

5.6.25

**Comment by trife** [comment]
I think it's this crash:

```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.fieldbook.tracker/com.fieldbook.tracker.activities.CollectActivity}: android.database.sqlite.SQLiteException: no such column: col_number (code 1 SQLITE_ERROR): , while compiling: SELECT `col_number`, `row_number`, `plot_name`, `id` FROM ObservationUnitProperty WHERE id = ?
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4832)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4865)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:223)
       at android.os.Looper.loop(Looper.java:317)
       at android.app.ActivityThread.main(ActivityThread.java:7942)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```

**Comment by chaneylc** [comment]
I can't reproduce this on the newest version, if the issue continues please reopen this or send me the database that's causing the error, thanks.
