### ISSUE TITLE
[BUG] CassavaBase BrAPI date formatting issue

### ISSUE THREAD

**Issue by trife** [PhenoApps/Field-Book#121]
**Describe the bug**
App crashes when attempting to connect to CassavaBase and download list of fields. The issue is related to the date formatting used for certain fields in Cassavabase.

**To Reproduce**
1. Authorize Field Book to connect to BrAPI
2. Attempt to import new field from BrAPI source

**Questions**
1. Is this an issue that can be solved by making changes to the javalib PhenoApp library?
2. Does/should BrAPI require a certain format for times/dates?

**LogCat**
```
2020-03-22 17:56:55.147 30993-31056/com.fieldbook.tracker E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.fieldbook.tracker, PID: 30993
    org.threeten.bp.format.DateTimeParseException: Text '2000-April-11' could not be parsed at index 5
        at org.threeten.bp.format.DateTimeFormatter.parseToBuilder(DateTimeFormatter.java:1588)
        at org.threeten.bp.format.DateTimeFormatter.parse(DateTimeFormatter.java:1491)
        at org.threeten.bp.LocalDate.parse(LocalDate.java:367)
        at io.swagger.client.JSON$LocalDateTypeAdapter.read(JSON.java:235)
        at io.swagger.client.JSON$LocalDateTypeAdapter.read(JSON.java:202)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        at com.google.gson.Gson.fromJson(Gson.java:897)
        at com.google.gson.Gson.fromJson(Gson.java:846)
        at io.swagger.client.JSON.deserialize(JSON.java:144)
        at io.swagger.client.ApiClient.deserialize(ApiClient.java:710)
        at io.swagger.client.ApiClient.handleResponse(ApiClient.java:913)
        at io.swagger.client.ApiClient$1.onResponse(ApiClient.java:879)
        at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

@ctucker3 @nickpalladino @lukasmueller @BrapiCoordinatorSelby @peterrosario

**Comment by peterrosario** [comment]
I just merged a branch from Selby that had date/time changes.  The merge is deployed as version 1.0.5.  Are you using the newest version (1.0.5) or an older one?
________________________________

**Comment by trife** [comment]
This happens when building with 1.0.5

**Comment by BrapiCoordinatorSelby** [comment]
related to this issue: https://github.com/PhenoLibs/JavaLibraryBuilder/issues/1
@ctucker3 did you have a work around in Breedbase for the images dates which should have been date times?
@MFlores2021 tagged for Breedbase API support

Answering the questions above:
(1) Maybe? The javalib should be able to handle both dates and timestamps. but the error has the text "_2000-April-11_" which is not valid. CassavaBase should provide "_2000-04-11_"
(2) yes, BrAPI uses ISO 8601 standard and should be expecting a 2 digit month. 
https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Date_Time_Encoding.md

**Comment by MFlores2021** [comment]
I just quickly checked images endpoints for breedbase and they have timestamp as required ex. 2012-07-24T15:34:34-0400. @ctucker3 is there any endpoint that need to be fix?

**Comment by ctucker3** [comment]
Hey guys, sorry just viewing in on this. Could this endpoint be the issue, 

http://cassavabase.org/brapi/v1/studies

the end dates and start dates seem to be culprits and match the date in your error message @trife . I am not sure why we haven't run into this before. I remember pulling from sweet potato base for testing, but that seems to also have end and start dates formatted that way.
