### ISSUE TITLE
[BUG] Collect Activity crashes after importing sample csv. Android Kitkat.

### ISSUE THREAD

**Issue by chaneylc** [PhenoApps/Field-Book#148]
**Describe the bug**
Related to https://github.com/PhenoApps/Field-Book/issues/146 but slightly different.
Similarly, the app crashes immediately on navigating to Collect Activity after importing the first sample csv.

**To Reproduce**
1. Press no to both dialogs.
2. Go to fields, import sample csv.
3. Go back to Config and click Collect.

**Device Info (please complete the following information):**
 - Model: AVD Pixel 1 4.4.2 KitKat

**Additional context**
Seems to be a problem with loading traits.

**Comment by chaneylc** [comment]
I made a new issue because the crash is different:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fieldbook.tracker, PID: 4091
    java.lang.NullPointerException
        at com.fieldbook.tracker.activities.CollectActivity.validateData(CollectActivity.java:280)
        at com.fieldbook.tracker.activities.CollectActivity.access$1800(CollectActivity.java:86)
        at com.fieldbook.tracker.activities.CollectActivity$RangeBox.moveEntryRight(CollectActivity.java:1727)
        at com.fieldbook.tracker.activities.CollectActivity$RangeBox.access$1100(CollectActivity.java:1319)
        at com.fieldbook.tracker.activities.CollectActivity$RangeBox$2.onClick(CollectActivity.java:1410)
        at android.view.View.performClick(View.java:4438)
        at com.fieldbook.tracker.activities.CollectActivity$RangeBox$9.onTouch(CollectActivity.java:1518)
