### ISSUE TITLE
[BUG] Trait db migration error

### ISSUE THREAD

**Issue by nickpalladino** [PhenoApps/Field-Book#221]
**Describe the bug**
Trait db migration fails due to trait categories in a trait being null in existing database:

```
W/System.err: java.lang.NullPointerException: null cannot be cast to non-null type kotlin.String
        at com.fieldbook.tracker.database.Migrator$Companion.createTables(Migrator.kt:207)
        at com.fieldbook.tracker.database.Migrator$Companion.migrateSchema(Migrator.kt:103)
        at com.fieldbook.tracker.database.DataHelper$OpenHelper.onUpgrade(DataHelper.java:2500)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
        at com.fieldbook.tracker.database.DataHelper.<init>(DataHelper.java:91)
```

**To Reproduce**
Have previous version of Field Book with traits containing null for categories and try to migrate to latest.

**Expected behavior**
Migration works without error.

**Device Info (please complete the following information):**
 - Model: [Nexus 6P Emulator API 23]
 - Field Book Version [e.g. 4.5]

**Comment by ctucker3** [comment]
@chaneylc @nickpalladino @trife  Is this still an issue? Looks like Chaney put in a fix on March 12th that should take of it:

https://github.com/PhenoApps/Field-Book/commit/634793fd51914dfab29381323d5db5af2fcfe7b6

**Comment by trife** [comment]
@ctucker3 Good catch!
