### ISSUE TITLE
[BUG] Java time API 26 or later

### ISSUE THREAD

**Issue by nickpalladino** [PhenoApps/Field-Book#222]
**Describe the bug**
Can't resolve java time class which looks to be only available on API 26 or later.

```
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/format/DateTimeFormatter;
        at org.brapi.client.v2.typeAdapters.OffsetDateTimeTypeAdapter.<init>(OffsetDateTimeTypeAdapter.java:19)
        at org.brapi.client.v2.JSON.<init>(JSON.java:43)
        at org.brapi.client.v2.BrAPIClient.init(BrAPIClient.java:97)
        at org.brapi.client.v2.BrAPIClient.<init>(BrAPIClient.java:87)
        at com.fieldbook.tracker.brapi.service.BrAPIServiceV2.<init>(BrAPIServiceV2.java:77)
        at com.fieldbook.tracker.brapi.service.BrAPIServiceFactory.getBrAPIService(BrAPIServiceFactory.java:15)
        at com.fieldbook.tracker.activities.BrapiActivity.onCreate(BrapiActivity.java:64)
```

**To Reproduce**
1. Set brapi version to V2
2. Try to import a study and field book will crash

**Expected behavior**
Import works without error

**Device Info (please complete the following information):**
 - Model: [Nexus 6P API 23]
 - Field Book Version [brapi_v2]

**Comment by BrapiCoordinatorSelby** [comment]
This one I can help with! 
In `brapi-java-model` I included a class called `TimeAdapter.java` 
Use the static methods in this class to convert between `java.time` and `org.threeten.bp`

**Comment by nickpalladino** [comment]
> This one I can help with!
> In `brapi-java-model` I included a class called `TimeAdapter.java`
> Use the static methods in this class to convert between `java.time` and `org.threeten.bp`

It seems like the `import java.time.format.DateTimeFormatter;` in OffsetDateTimeTypeAdapter.java needs to be replaced with `import org.threeten.bp.format.DateTimeFormatter;` to work on API < 26. Maybe I'm missing something. Let me know.

**Comment by BrapiCoordinatorSelby** [comment]
I don't know the full history of what happened in the java community, but to my understanding `java.time` and `org.threeten.bp` are almost exactly the same BUT they are not compatible with each other.  Within a jar, if you start using one of them, you have to use it everywhere. So if you switched to `import org.threeten.bp.format.DateTimeFormatter;` you would have to change everything in `brapi-java-client` to match. But `java.time` is the better updated and maintained package and it will be the best choice going forward, so I don't think `brapi-java-client` should switch.
I also don't really understand the Android API checking system, because it only seems to care about code directly in the android project, external JARs can do whatever they want. The Field Book code cannot use `java.time` because it violates the API limit, but the Field Book code will happily call out to the `brapi-java-client` jar and ask it to convert things into `org.threeten.bp`. I don't have access to a lower API device to test this on, so maybe it breaks at runtime, but Android Studio doesn't complain at least.

**Comment by nickpalladino** [comment]
> Field Book code will happily call out to the `brapi-java-client` jar and ask it to convert things into `org.threeten.bp`. I don't have access to a lower API device to test this on, so maybe it breaks at runtime, but Android Studio doesn't complain at least.

Ya, I think you would see runtime issues if you tried it on API < 26. I was looking through the old org.phenoapps:javalib:1.0.5 client used for the brapi v1.3 stuff and it looks like it's using org.threeten which is probably why we didn't have problems before. I found https://stackoverflow.com/questions/38922754/how-to-use-threetenabp-in-android-project which talks about api desugaring to be able to use java.time in older api versions. I'm messing with it now a bit.

**Comment by chaneylc** [comment]
@nickpalladino What server are you using? I tried reproducing this using the test server and I'm not getting a crash. Although similarly, I was getting `java.time.format.DateTimeParseException: Text '2000-04-11' could not be parsed at index 10` when trying to getStudiesAsync from cassavabase specifically.

**Comment by nickpalladino** [comment]
@chaneylc The server shouldn't matter but I'm using a development breedbase server. Are you running an android device with API < 26?

**Comment by chaneylc** [comment]
🤦‍♂️ I was thinking this was for API 26 or later, mb
I was just curious with the server because @trife and I recently found many dates in cassavabase: [ "2000-07-26",
  "2000-08-01"] which all cause date time formatting issues. Try GET studies on v2 branch for cassavabase and you get:
  `java.time.format.DateTimeParseException: Text '2000-04-11' could not be parsed at index 10` in the fail callback. Although, this is definitely a separate issue.

**Comment by nickpalladino** [comment]
No problem, ah I see. I made that api sugaring change and it fixed java.time but then was causing weird gson deserializing problems like those discussed at https://github.com/getsentry/sentry-android/issues/476. I upgraded Android Studio & gradle to 4.1.2 and used the latest com.android.tools:desugar_jdk_libs and that fixed the issue for API < 26. API >= 26 emulator was being a little funky but seems like it's unrelated. I pushed the changes up.
