### ISSUE TITLE
[BUG] Add Bluetooth permission check to GNSS trait

### ISSUE THREAD

**Issue by trife** [PhenoApps/Field-Book#434]

**Comment by trife** [comment]
Also unable to scan for devices? This happens when re-selecting internal (after selecting internal from the GeoNav settings).

```
2022-05-13 17:55:34.758 16335-16335/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fieldbook.tracker, PID: 16335
    java.lang.SecurityException: Need android.permission.BLUETOOTH_SCAN permission for android.content.AttributionSource@c588c75d: AdapterService cancelDiscovery
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
        at android.os.Parcel.createException(Parcel.java:2409)
        at android.os.Parcel.readException(Parcel.java:2392)
        at android.os.Parcel.readException(Parcel.java:2334)
        at android.bluetooth.IBluetooth$Stub$Proxy.cancelDiscovery(IBluetooth.java:2945)
        at android.bluetooth.BluetoothAdapter.cancelDiscovery(BluetoothAdapter.java:1863)
        at com.fieldbook.tracker.traits.GNSSTraitLayout.setupCommunicationsUi(GNSSTraitLayout.kt:520)
        at com.fieldbook.tracker.traits.GNSSTraitLayout.findPairedDevice$lambda-12(GNSSTraitLayout.kt:504)
        at com.fieldbook.tracker.traits.GNSSTraitLayout.$r8$lambda$MCoKSpD6-gK7dDmGYkhw-sS1-KE(Unknown Source:0)
        at com.fieldbook.tracker.traits.GNSSTraitLayout$$ExternalSyntheticLambda2.onClick(Unknown Source:6)
        at androidx.appcompat.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1068)
        at android.widget.AdapterView.performItemClick(AdapterView.java:330)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1197)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3190)
        at android.widget.AbsListView$3.run(AbsListView.java:4166)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```
