### ISSUE TITLE
[BUG]: Issue with brapi export

### ISSUE THREAD

**Issue by trife** [PhenoApps/Field-Book#617]
### Description

````
Fatal Exception: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
       at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:11586)
       at android.view.ViewRootImpl.focusableViewAvailable(ViewRootImpl.java:6257)
       at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:972)
       at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:972)
       at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:972)
       at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:972)
       at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:972)
       at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:972)
       at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:972)
       at android.view.View.setFlags(View.java:17904)
       at android.view.View.setEnabled(View.java:12714)
       at android.widget.TextView.setEnabled(TextView.java:2617)
       at com.fieldbook.tracker.activities.BrapiExportActivity.hideSaving(BrapiExportActivity.java:252)
       at com.fieldbook.tracker.activities.BrapiExportActivity.uploadComplete(BrapiExportActivity.java:510)
       at com.fieldbook.tracker.activities.BrapiExportActivity.lambda$createObservations$3$com-fieldbook-tracker-activities-BrapiExportActivity(BrapiExportActivity.java:277)
       at com.fieldbook.tracker.activities.BrapiExportActivity$$ExternalSyntheticLambda0.apply(:4)
       at com.fieldbook.tracker.brapi.service.AbstractBrAPIService.lambda$saveChunks$1(AbstractBrAPIService.java:66)
       at com.fieldbook.tracker.brapi.service.AbstractBrAPIService$$ExternalSyntheticLambda0.apply(:13)
       at com.fieldbook.tracker.brapi.service.BrAPIServiceV1$11.onFailure(BrAPIServiceV1.java:681)
       at io.swagger.client.ApiClient$1.onResponse(ApiClient.java:881)
       at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
       at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)
````

### Field Book version

5.3

**Comment by trife** [comment]
````
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fieldbook.tracker/com.fieldbook.tracker.activities.brapi.BrapiExportActivity}: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter traitName
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4169)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
````


````
Caused by java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter traitName
       at com.fieldbook.tracker.utilities.DocumentTreeUtil$Companion.getFieldMediaDirectory(:3)
       at com.fieldbook.tracker.brapi.model.FieldBookImage.<init>(FieldBookImage.java:49)
       at com.fieldbook.tracker.database.dao.ObservationDao$Companion$getUserTraitImageObservations$1.invoke(ObservationDao.kt:209)
       at com.fieldbook.tracker.database.dao.ObservationDao$Companion$getUserTraitImageObservations$1.invoke(ObservationDao.kt:206)
       at com.fieldbook.tracker.database.SqlUtilKt.withDatabase(SqlUtil.kt:166)
       at com.fieldbook.tracker.database.dao.ObservationDao$Companion.getUserTraitImageObservations(ObservationDao.kt:206)
       at com.fieldbook.tracker.database.DataHelper.getUserTraitImageObservations(DataHelper.java:416)
       at com.fieldbook.tracker.activities.brapi.BrapiExportActivity.loadStatistics(BrapiExportActivity.java:704)
       at com.fieldbook.tracker.activities.brapi.BrapiExportActivity.onCreate(BrapiExportActivity.java:118)
       at android.app.Activity.performCreate(Activity.java:8591)
       at android.app.Activity.performCreate(Activity.java:8570)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
````
