### ISSUE TITLE
[BUG]: exporting observations fail for the new version

### ISSUE THREAD

**Issue by MFlores2021** [PhenoApps/Field-Book#630]
### Description

I have tested with Ryan Crawford to export to breedbase some data using Fieldbook and brapi. But it crashed for Fieldbook 5.4 and exported successfully for version 5.3

**Comment by trife** [comment]
What type of device? Is this on an up-to-date breedbase installation?

**Comment by joegage** [comment]
@trife we are seeing similar issues; as far as I can tell our breedbase is up to date and fieldbook is the latest build on a Moto Play G

Not sure if the behavior is exactly the same as what @MFlores2021 is reporting, but a description of the behavior we are seeing (this was sent to @BrapiCoordinatorSelby independently by @krfritz earlier today):

We are using BrAPI V2 to import and export between Fieldbook version [5.4.5.10](https://github.com/PhenoApps/Field-Book/tree/5.4.5.10) and Breedbase. We have successfully imported our fields and trait ontologies using BrAPI but when exporting observations we are having some issues. When exporting observations I receive an error saying "BrAPI Export Failed" but I am then able to see the data that I have collected within Breedbase. If I go to collect more observations then and try to export them again to Breedbase I receive the same error message but then my observations do not show up in Breedbase. If I first delete the previous file though then they will upload.

**Comment by trife** [comment]
@BrapiCoordinatorSelby do you think this is related to a malformed `observationDbId` response?

**Comment by trife** [comment]
On the Field Book side, it looks like this crash is due to a UI bug, but one that's only happening after the export already fails. @chaneylc
````
Fatal Exception: java.lang.NullPointerException: Can't toast on a thread that has not called Looper.prepare()
       at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:157)
       at android.widget.Toast.getLooper(Toast.java:179)
       at android.widget.Toast.<init>(Toast.java:164)
       at android.widget.Toast.makeText(Toast.java:492)
       at android.widget.Toast.makeText(Toast.java:480)
       at com.fieldbook.tracker.brapi.service.BrAPIService$-CC.handleConnectionError(BrAPIService.java:153)
       at com.fieldbook.tracker.activities.brapi.BrapiExportActivity.uploadComplete(BrapiExportActivity.java:533)
       at com.fieldbook.tracker.activities.brapi.BrapiExportActivity.lambda$createObservations$4$com-fieldbook-tracker-activities-brapi-BrapiExportActivity(BrapiExportActivity.java:295)
       at com.fieldbook.tracker.activities.brapi.BrapiExportActivity$$ExternalSyntheticLambda0.apply(:4)
       at com.fieldbook.tracker.brapi.service.AbstractBrAPIService.lambda$saveChunks$1(AbstractBrAPIService.java:66)
       at com.fieldbook.tracker.brapi.service.AbstractBrAPIService$$ExternalSyntheticLambda0.apply(:13)
       at com.fieldbook.tracker.brapi.service.BrAPIServiceV2$12.onFailure(BrAPIServiceV2.java:793)
       at org.brapi.client.v2.BrAPIClient$2.onResponse(BrAPIClient.java:864)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
````

**Comment by BrapiCoordinatorSelby** [comment]
> do you think this is related to a malformed observationDbId response?
That seems plausible, but I haven't had a chance to dig into it
