### ISSUE TITLE
Tutorial crashes app

### ISSUE THREAD

**Issue by trife** [PhenoApps/Field-Book#631]

**Comment by bellerbrock** [comment]
Here's the error from logcat:
```
FATAL EXCEPTION: main
                                                                                                    Process: com.fieldbook.tracker, PID: 5336
                                                                                                    android.content.res.Resources$NotFoundException: Resource ID #0xff689f38
                                                                                                    	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:226)
                                                                                                    	at android.content.res.Resources.getColor(Resources.java:1068)
                                                                                                    	at android.content.Context.getColor(Context.java:794)
                                                                                                    	at androidx.core.content.ContextCompat$Api23Impl.getColor(ContextCompat.java:1034)
                                                                                                    	at androidx.core.content.ContextCompat.getColor(ContextCompat.java:578)
                                                                                                    	at com.getkeepsafe.taptargetview.TapTarget.colorResOrInt(TapTarget.java:489)
                                                                                                    	at com.getkeepsafe.taptargetview.TapTarget.outerCircleColorInt(TapTarget.java:455)
                                                                                                    	at com.getkeepsafe.taptargetview.TapTargetView.applyTargetOptions(TapTargetView.java:588)
                                                                                                    	at com.getkeepsafe.taptargetview.TapTargetView.<init>(TapTargetView.java:427)
                                                                                                    	at com.getkeepsafe.taptargetview.TapTargetView.showFor(TapTargetView.java:166)
                                                                                                    	at com.getkeepsafe.taptargetview.TapTargetSequence.showNext(TapTargetSequence.java:193)
                                                                                                    	at com.getkeepsafe.taptargetview.TapTargetSequence.start(TapTargetSequence.java:126)
                                                                                                    	at com.fieldbook.tracker.activities.ConfigActivity.onOptionsItemSelected(ConfigActivity.java:944)
```
outerCircleColor was not getting resolved correctly in [TapTargetUtil.kt](https://github.com/PhenoApps/Field-Book/blob/main/app/src/main/java/com/fieldbook/tracker/utilities/TapTargetUtil.kt). Same with the other colors, though they all are optional with what seem like sensible defaults.

I refactored the outerCircleColor resolution to get the color for the active theme. The crash problem is fixed, but the CollectActivity tutorial is still buggy if using the High Contrast theme - R.attr.fb_color_primary resolves to white, which means text within it isn't visible. The simplest solution I see would be to modify the collectactivity tutorial to use all R.attr.fb_color_primary_dark outer circles, which is what the other tutorials do. Does that sound reasonable?

**Comment by trife** [comment]
That sounds good to me

**Comment by bellerbrock** [comment]
Ok. All done, should be good to review and merge.
