### ISSUE TITLE
[BUG]: Adding field in Fieldbook from BMS using BrAPI: No Categories for categorical traits.

### ISSUE THREAD

**Issue by jpietragalla** [PhenoApps/Field-Book#640]
### Description

When connecting BMS and Fieldbook App for loading Fields (Studies in BMS) there is an issue for the traits that are Categorical. There valid categories are no recive in the Fieldbook App.

Steps to reproduce it:

1. Create a study in BMS. Add Traits in Observations tab, be sure at least one trait is Categorical.

![image](https://github.com/PhenoApps/Field-Book/assets/78973920/f6d107a5-6eff-4e97-a376-c92bd98ec3d5)

2. Connect KSU Fieldbook to BMS using BrAPI. (Using

3. In the App, go to Fields and add a Study using BrAPI

4. Go to Traits and open the Categorical Trait to see the categories. Or go to Collect and move to the Categorical trait.

Video of the steps: https://drive.google.com/file/d/12HN7LiOFA1-Y66XHpsDif-v4f_ppKbqH/view?usp=sharing

Actual result
KSU Fieldbook DO NOT display the Categories for the categorical trait.
![image](https://github.com/PhenoApps/Field-Book/assets/78973920/da89ee22-58d2-4cdd-b18f-f808b913d954)
![image](https://github.com/PhenoApps/Field-Book/assets/78973920/3e6a3fdd-71b9-49e0-b5ae-29f23fa8acb9)

Video of the steps:

Note: Tested in old versions of Fieldbook app (5.2.0) against BMS v24 and the categories are displayed properly in the app. In Version 5.3 and 5.4 (Beta) is not working properly.

### Expected behavior

KSU Fieldbook display the Categories for the categorical trait. Categories are send to the App in the correct order.
![image](https://github.com/PhenoApps/Field-Book/assets/78973920/a89ce4b6-abf3-461f-ad10-a996b5fdfef8)

### Field Book version

5.3.0 and 5.4.0

**Comment by abatac** [comment]
This issue still happens in Fieldbook v5.3 connected to BMS BrAPI v1.3. 

It seems that Fieldbook app doesn't process the values in the trait categories even though these are returned from BMS.

Here is the sample data returned from BMS Brapi v1.3 in getting study observation variables:
`/brapi/v1/studies/{studyDbid}/observationvariables`
```
{
  "metadata": {
    "pagination": {
      "currentPage": 0,
      "pageSize": 1000,
      "totalCount": 1,
      "totalPages": 1
    },
    "status": [],
    "datafiles": []
  },
  "result": {
    "data": [
      {
        "contextOfUse": [
          "PLOT"
        ],
        "crop": "maize",
        "date": null,
        "defaultValue": "",
        "documentationURL": null,
        "growthStage": null,
        "institution": null,
        "language": null,
        "name": "AleuCol_E_1to5",
        "observationVariableDbId": "51547",
        "observationVariableName": "AleuCol_E_1to5",
        "ontologyReference": {
          "documentationLinks": [],
          "ontologyDbId": "51547",
          "ontologyName": "AleuCol_E_1to5",
          "version": null
        },
        "trait": {
          "alternativeAbbreviations": [],
          "attribute": null,
          "entity": null,
          "mainAbbreviation": null,
          "description": "Color of the aleurone.",
          "name": "Aleurone color",
          "status": "Active",
          "synonyms": [],
          "traitDbId": "51447",
          "traitName": "Aleurone color",
          "xref": "CO_322:0000190",
          "ontologyReference": {
            "documentationLinks": [],
            "ontologyDbId": "CO_322:0000190",
            "ontologyName": "Aleurone color",
            "version": null
          },
          "class": "Morphological"
        },
        "method": {
          "description": "Observe the aleurone color, when applicable, on at least 20 representative plants per accession.",
          "formula": "null",
          "methodDbId": "62172",
          "methodName": "AleuCol - Estimation",
          "name": "AleuCol - Estimation",
          "ontologyReferenceObject": {
            "documentationLinks": [],
            "ontologyDbId": "62172",
            "ontologyName": "AleuCol - Estimation",
            "version": null
          },
          "reference": null,
          "ontologyReference": {
            "documentationLinks": [],
            "ontologyDbId": "62172",
            "ontologyName": "AleuCol - Estimation",
            "version": null
          },
          "class": null
        },
        "scale": {
          "dataType": "Nominal",
          "decimalPlaces": null,
          "name": "1-5 Aleurone color scale",
          "ontologyReference": {
            "documentationLinks": [],
            "ontologyDbId": "62173",
            "ontologyName": "1-5 Aleurone color scale",
            "version": null
          },
          "scaleDbId": "62173",
          "scaleName": "1-5 Aleurone color scale",
          "validValues": {
            "categories": [
              "1",
              "2",
              "3",
              "4",
              "5"
            ],
            "max": null,
            "min": null
          },
          "xref": null
        },
        "scientist": null,
        "status": null,
        "submissionTimestamp": null,
        "synonyms": [],
        "xref": null
      }
    ],
    "studyDbId": "13",
    "trialName": "Study5"
  }
}
```

**Comment by trife** [comment]
@jpietragalla @abatac Please test out the [generated apk](https://github.com/PhenoApps/Field-Book/pull/647#issuecomment-1611851325) to see if this issue persists.

**Comment by abatac** [comment]
> @jpietragalla @abatac Please test out the [generated apk](https://github.com/PhenoApps/Field-Book/pull/647#issuecomment-1611851325) to see if this issue persists.

We tested the apk but it has issues with BrAPI Field Import. When the Preview Field button is clicked, the application crashes.

I looked at the logs and I see these errors:

```
2023-06-29 10:49:21.211 16444-16556/? E/BrAPIServiceV1: Error fetching observation levels
    io.swagger.client.ApiException: 
        at io.swagger.client.ApiClient.handleResponse(ApiClient.java:924)
        at io.swagger.client.ApiClient$1.onResponse(ApiClient.java:879)
        at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)
```

```
2023-06-29 10:42:17.314 15715-15715/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fieldbook.tracker, PID: 15715
    java.lang.IllegalStateException: Could not execute method for android:onClick
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:446)
        at android.view.View.performClick(View.java:7506)
        at android.view.View.performClickInternal(View.java:7483)
        at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
        at android.view.View$PerformClick.run(View.java:29335)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7929)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:441)
        at android.view.View.performClick(View.java:7506) 
        at android.view.View.performClickInternal(View.java:7483) 
        at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0) 
        at android.view.View$PerformClick.run(View.java:29335) 
        at android.os.Handler.handleCallback(Handler.java:942) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7929) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.fieldbook.tracker.brapi.model.BrapiObservationLevel.getObservationLevelName()' on a null object reference
        at com.fieldbook.tracker.brapi.service.BrAPIServiceV1.getPlotDetails(BrAPIServiceV1.java:511)
        at com.fieldbook.tracker.brapi.BrapiLoadDialog.buildStudyDetails(BrapiLoadDialog.java:158)
        at com.fieldbook.tracker.brapi.BrapiLoadDialog.onStart(BrapiLoadDialog.java:94)
        at android.app.Dialog.show(Dialog.java:333)
        at com.fieldbook.tracker.activities.brapi.BrapiActivity.saveStudy(BrapiActivity.java:242)
        at com.fieldbook.tracker.activities.brapi.BrapiActivity.buttonClicked(BrapiActivity.java:226)
        at java.lang.reflect.Method.invoke(Native Method) 
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:441) 
        at android.view.View.performClick(View.java:7506) 
        at android.view.View.performClickInternal(View.java:7483) 
        at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0) 
        at android.view.View$PerformClick.run(View.java:29335) 
        at android.os.Handler.handleCallback(Handler.java:942) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7929) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
```

**Comment by trife** [comment]
@chaneylc I'm seeing the same behavior.

**Comment by chaneylc** [comment]
This is a different bug. I'll look into it today and include a fix in this linked PR. Importing categorical traits through the trait editor should work correctly with the pre built APK.

**Comment by chaneylc** [comment]
I fixed the obs. levels problem, but now there is an authentication error I'm figuring out.

**Comment by trife** [comment]
@jpietragalla @abatac Please test out the https://github.com/PhenoApps/Field-Book/pull/647#issuecomment-1611851325 to see if this issue has been fixed.

**Comment by abatac** [comment]
Sorry for the late reply, we tested the APK and we have encountered this error below. I also notice that the Observation level dropdown is not populated.

![image](https://github.com/PhenoApps/Field-Book/assets/5011207/c87dc730-bd95-4090-8f0f-106ecf1a02ef)
