### ISSUE TITLE
[BUG]: BrAPI Sync is hanging

### ISSUE THREAD

**Issue by joegage** [PhenoApps/Field-Book#648]
### Description

When I try to sync observations for a field via BrAPI, the dialog box titled "Downloading Observations for Study:" appears, along with a spinning circle. The phone will stay in this state for hours (overnight even). If I press 'Cancel', operation resumes as normal but no traits are synced.

In our breedbase logs, I do see some psql commands when the sync is initiated (example below), but nothing else in the log while the circle spins or when I cancel.

```
$VAR_DUMP1 = 'SELECT (((cvterm.name::text || \'|\'::text) || db.name::text) || \':\'::text) || dbxref.accession::text AS trait, cvterm.cvterm_id, imaging_project.project_id, imaging_project.name, count(phenotype.value)
            FROM cvterm
            
            JOIN dbxref ON (cvterm.dbxref_id = dbxref.dbxref_id)
            JOIN db ON (dbxref.db_id = db.db_id)
            JOIN phenotype ON (cvterm.cvterm_id=phenotype.cvalue_id)
            JOIN nd_experiment_phenotype USING(phenotype_id)
            JOIN nd_experiment_project USING(nd_experiment_id)
            LEFT JOIN phenome.nd_experiment_md_images AS nd_experiment_md_images USING(nd_experiment_id)
            LEFT JOIN phenome.project_md_image AS project_md_image ON (nd_experiment_md_images.image_id=project_md_image.image_id)
            LEFT JOIN project AS imaging_project ON (project_md_image.project_id=imaging_project.project_id)
            WHERE nd_experiment_project.project_id=? 
            GROUP BY trait, cvterm.cvterm_id, imaging_project.project_id, imaging_project.name
            ORDER BY trait;';
Use of uninitialized value $_ in substitution (s///) at lib/CXGN/BrAPI/v2/ObservationVariables.pm line 175.
Use of uninitialized value $_ in substitution (s///) at lib/CXGN/BrAPI/v2/ObservationVariables.pm line 176.
Use of uninitialized value $_ in substitution (s///) at lib/CXGN/BrAPI/v2/ObservationVariables.pm line 175.
Use of uninitialized value $_ in substitution (s///) at lib/CXGN/BrAPI/v2/ObservationVariables.pm line 176.
Synonym Start:Thu Jun 29 14:46:41 2023
Synonym End:Thu Jun 29 14:46:41 2023
QUERY: SELECT observationunit_stock_id, observationunit_uniquename, observationunit_type_name, germplasm_uniquename, germplasm_stock_id, rep, block, plot_number, row_number, col_number, plant_number, is_a_control, notes, trial_id, trial_name, trial_description, plot_width, plot_length, field_size, field_trial_is_planned_to_be_genotyped, field_trial_is_planned_to_cross, breeding_program_id, breeding_program_name, breeding_program_description, year, design, location_id, planting_date, harvest_date, folder_id, folder_name, folder_description, seedlot_transaction, seedlot_stock_id, seedlot_uniquename, seedlot_current_weight_gram, seedlot_current_count, seedlot_box_name, available_germplasm_seedlots, treatments, observations, count(observationunit_stock_id) OVER() AS full_count FROM materialized_phenotype_jsonb_table  WHERE trial_id in (182) AND (observationunit_type_name = 'plot' OR observationunit_type_name = 'plant' OR observationunit_type_name = 'subplot' OR observationunit_type_name = 'tissue_sample') ORDER BY trial_name, observationunit_uniquename

Search End:Thu Jun 29 14:46:44 2023
```

### Expected behavior

Syncing fields should pull down previously collected trait data from our BreedBase server without hanging.

### Field Book version

5.4.7.12

**Comment by trife** [comment]
Awesome, thanks!

**Comment by joegage** [comment]
Thanks @zrm22 - still not working though! I am seeing this error in the phone's logs when I try to sync. Behavior on screen is the same as before:

`API Exception
org.brapi.client.v2.model.exceptions.ApiException: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 90 path $.result.data[0].season
	at org.brapi.client.v2.BrAPIClient$2.onResponse(BrAPIClient.java:867)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 90 path $.result.data[0].season
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at org.brapi.client.v2.JSON.deserialize(JSON.java:111)
	at org.brapi.client.v2.BrAPIClient.deserialize(BrAPIClient.java:651)
	at org.brapi.client.v2.BrAPIClient.handleResponse(BrAPIClient.java:896)
	at org.brapi.client.v2.BrAPIClient$2.onResponse(BrAPIClient.java:862)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
	at java.lang.Thread.run(Thread.java:923) 
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 90 path $.result.data[0].season
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:386)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) 
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) 
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) 
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) 
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) 
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) 
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) 
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) 
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) 
	at com.google.gson.Gson.fromJson(Gson.java:932) 
	at com.google.gson.Gson.fromJson(Gson.java:897) 
	at com.google.gson.Gson.fromJson(Gson.java:846) 
	at org.brapi.client.v2.JSON.deserialize(JSON.java:111) 
	at org.brapi.client.v2.BrAPIClient.deserialize(BrAPIClient.java:651) 
	at org.brapi.client.v2.BrAPIClient.handleResponse(BrAPIClient.java:896) 
	at org.brapi.client.v2.BrAPIClient$2.onResponse(BrAPIClient.java:862) 
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
	at java.lang.Thread.run(Thread.java:923) 
`

**Comment by zrm22** [comment]
Is this being thrown when you attempt to sync?  

I could be wrong, but this seems to be when Fieldbook is attempting to parse the JSON object coming in through BrAPI but something is wrong with the format of the JSON response.  Can you verify that you can get observations through BrAPI with the trial you are trying to sync?

**Comment by zrm22** [comment]
I met with @joegage over zoom to try to debug this.  It looks like it is falling to be within the Fail function on the BrAPI v2 BrAPIObservationListResponse callback.  I think this is because the library is unable to parse the response correctly on the first page of observations before it even gets into the Fieldbook code.  The Traits are loading fine, and we tried some manual BrAPI calls and everything looked ok.  This is working on the Buckler Lab deployment of BreedingInsight's Breedbase(from around March), but for some reason it is not working for @joegage 's.

**Comment by joegage** [comment]
@BrapiCoordinatorSelby any idea what is causing this to fail on the BrAPI side? Would be happy to meet and show you what @zrm22 and I found.

**Comment by BrapiCoordinatorSelby** [comment]
This is your smoking gun 
```
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 90 path $.result.data[0].season at 
```

Looks like Breedbase has `"season" : [ { "seasonDbId" etc } ]` an array of seasons for each observation. 
The BrAPI spec has `"season" : { "seasonDbId" etc }` just a single season object for each observation. Studies can have an array of seasons, but a single observation can only occur in one season.

Pass this to the Breedbase team to fix

**Comment by BrapiCoordinatorSelby** [comment]
That said...
@zrm22 While I was looking at this issue, I tried to sync a study that had no observations. It also failed to show the "save" button to me. I debugged a little and found that it had `paginationManager.page` == 1 and `paginationManager.totalPages` == 0, so the equality read `1 == -1 ` and was never true. 
I might suggest changing it to a greater than instead of an equality, for safety, making sure it always ends the spinner eventually. I didn't dig much further so I don't know if this makes sense or if there is an easier way.

**Comment by zrm22** [comment]
@BrapiCoordinatorSelby Sure.  I will try to get that change in soon.  One question though, does it make sense for 'Save' to show up if there is nothing there?  Would it be better to hide the spinner then say no observations found and only show the cancel?  Might be a better question for @trife?

**Comment by BrapiCoordinatorSelby** [comment]
that is an excellent point. Maybe not save, just something to indicate that processing is done and the user doesn't need to wait anymore.

**Comment by trife** [comment]
Closing for now- reopen if this is still an issue.
