### ISSUE TITLE
[BUG]: Go pro bug

### ISSUE THREAD

**Issue by kamathprasad9** [PhenoApps/Field-Book#812]
### Description

The app crashes when navigating through the traits and passing across the go pro trait 

Stack trace:

`FATAL EXCEPTION: main
                                                                                                    Process: com.fieldbook.tracker, PID: 6134
                                                                                                    java.lang.NullPointerException: act.findViewById(R.id.go_pro_pv) must not be null
                                                                                                    	at com.fieldbook.tracker.traits.GoProTraitLayout.initWork(GoProTraitLayout.kt:155)
                                                                                                    	at com.fieldbook.tracker.traits.GoProTraitLayout.init$lambda$0(GoProTraitLayout.kt:185)
                                                                                                    	at com.fieldbook.tracker.traits.GoProTraitLayout.$r8$lambda$-KAQC_AdX5sX4D6MLOP9nbl5-u8(Unknown Source:0)
                                                                                                    	at com.fieldbook.tracker.traits.GoProTraitLayout$$ExternalSyntheticLambda15.run(Unknown Source:4)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)`

### Field Book version

5.5.24

**Comment by kamathprasad9** [comment]
Device: Google Pixel 6a
Operating System: Android 14
This is a physical device

Additional info
Android SDK version: 34
Build Number: UP1A.231105.003

**Comment by trife** [comment]
Fixed in 5.6.3
